use_frameworks!

platform :ios, '8.0'

target 'WJNetworking_Example' do
  pod 'WJNetworking', :path => '../'

  target 'WJNetworking_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
